// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCws32ZiL59u2wDKBytTLt99-08P_fMyMA',
    appId: '1:541306690870:web:4313266eae2690c0362797',
    messagingSenderId: '541306690870',
    projectId: 'firestore-61324',
    authDomain: 'firestore-61324.firebaseapp.com',
    storageBucket: 'firestore-61324.appspot.com',
    measurementId: 'G-GKDVB6JVFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5oiT7ObWi-thdXpwJXPrlDGO2f8mJac',
    appId: '1:541306690870:android:92498785b5e7ea9b362797',
    messagingSenderId: '541306690870',
    projectId: 'firestore-61324',
    storageBucket: 'firestore-61324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBqtqSI9d34T80oKp0lfx_npQY9AWi3M',
    appId: '1:541306690870:ios:f64a567f2cc78553362797',
    messagingSenderId: '541306690870',
    projectId: 'firestore-61324',
    storageBucket: 'firestore-61324.appspot.com',
    iosBundleId: 'com.example.movieBoxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoBqtqSI9d34T80oKp0lfx_npQY9AWi3M',
    appId: '1:541306690870:ios:b00bb3ecf372e373362797',
    messagingSenderId: '541306690870',
    projectId: 'firestore-61324',
    storageBucket: 'firestore-61324.appspot.com',
    iosBundleId: 'com.example.movieBoxApp.RunnerTests',
  );
}
